spring.application.name=autos

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=autos;encrypt=true;trustServerCertificate=true;
spring.datasource.username=autos
spring.datasource.password=autos
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Opcional: configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

